rabbitmq:
  url: "amqp://oleksandr:secret@rabbitmq:5672"
  vhost: "source_data_vhost"
  queue: "source_data_queue"

database:
  dsn: "homestead:secret@tcp(mysql:3306)/laravel_app"

consumer:
  workers: 5
