services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goapp
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    external: true